insert into instrument (name) values
('guitarra electrica'),
('guitarra acustica'),
('bajo electrico'),
('bajo acustico'),
('bateria'),
('piano'),
('piano electrico'),
('teclado'),
('sintetizador'),
('organo'),
('violin'),
('viola'),
('violonchelo'),
('contrabajo'),
('arpa'),
('ukelele'),
('banjo'),
('mandolina'),
('saxofon'),
('saxofon alto'),
('saxofon tenor'),
('saxofon soprano'),
('trompeta'),
('trombon'),
('tuba'),
('corno frances'),
('clarinete'),
('flauta'),
('flauta travesera'),
('oboe'),
('fagot'),
('armonica'),
('acordeon'),
('melodica'),
('congas'),
('bongos'),
('timbales'),
('cajon'),
('pandereta'),
('maracas'),
('xilofono'),
('vibrafono'),
('campanas'),
('triangulo'),
('gong'),
('djembe'),
('tabla'),
('didgeridoo'),
('charango'),
('balalaika');

insert into style (name) values
('rock'),
('pop'),
('jazz'),
('blues'),
('reggae'),
('ska'),
('hip hop'),
('rap'),
('trap'),
('r&b'),
('soul'),
('funk'),
('disco'),
('metal'),
('heavy metal'),
('thrash metal'),
('death metal'),
('black metal'),
('punk'),
('punk rock'),
('hardcore punk'),
('grunge'),
('indie'),
('indie rock'),
('alternativo'),
('electronic'),
('techno'),
('house'),
('deep house'),
('trance'),
('drum and bass'),
('dubstep'),
('ambient'),
('lo-fi'),
('synthwave'),
('country'),
('folk'),
('bluegrass'),
('flamenco'),
('latin'),
('salsa'),
('bachata'),
('merengue'),
('cumbia'),
('reggaeton'),
('bossa nova'),
('samba'),
('tango'),
('clasica'),
('opera'),
('gospel'),
('new age'),
('experimental'),
('instrumental');

INSERT INTO city (name) VALUES
('Algeciras'),
('Arcos de la Frontera'),
('Barbate'),
('Barrios Los'),
('Benalup-Casas Viejas'),
('Cadiz'),
('Chiclana de la Frontera'),
('Chipiona'),
('Conil de la Frontera'),
('El Puerto de Santa Maria'),
('Jerez de la Frontera'),
('La Linea de la Concepcion'),
('San Fernando'),
('San Roque'),
('Tarifa'),
('Ubrique'),
('Vejer de la Frontera'),
('Puerto Real'),
('Medina Sidonia'),
('Setenil de las Bodegas'),
('Rota'),
('San Martin del Tesorillo'),
('Trebujena'),
('Puerto de Santa Maria'),
('Jimena de la Frontera');